[build]
  command = "npm run build"
  publish = "dist"

[build.optimization]
  css = true
  js = true

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://blog-app-production-16c2.up.railway.app https://jonis-portfolio.netlify.app 'unsafe-inline' 'unsafe-eval';
      script-src-elem 'self' https://blog-app-production-16c2.up.railway.app https://jonis-portfolio.netlify.app 'unsafe-inline' 'unsafe-eval';
      style-src 'self' 'unsafe-inline' https://blog-app-production-16c2.up.railway.app;
      connect-src 'self' https://blog-app-production-16c2.up.railway.app https://portfolio-backend-k9okia.fly.dev;
      img-src 'self' https://blog-app-production-16c2.up.railway.app https://jonis-portfolio.netlify.app;
      object-src 'none';
      frame-src 'none';
      upgrade-insecure-requests;
    """
    X-Content-Type-Options = "nosniff"
